# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Setup
title:            DEWH
tagline:          IT
description:      des
url:              http://YWHyuk.github.io
baseurl:          /

layouts_dir         : _layouts
includes_dir        : _includes

paginate:         2
paginate_path:    "/page:num/"
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/YWHyuk
