# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      IT&Tech
url:              https://YWHyuk.github.io
baseurl:          /

paginate:         5



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/YWHyuk/YWHyuk.github.io/
