# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Setup
title:            DEWH
tagline:          IT
description:      Related to computer technology
url:              https://YWHyuk.github.io
baseurl:          https://YWHyuk.github.io/

layouts_dir         : _layouts
includes_dir        : _includes

paginate:         2
paginate_path:    "/page:num/"
categories:       [ A,B ]
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/YWHyuk
